// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Typo from "../../Typo.res.mjs";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import VideoJs from "video.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Css from "@emotion/css";
import * as JsxRuntime from "react/jsx-runtime";

import 'video.js/dist/video-js.css'
;

var wrapper = Css.css({
      height: "calc(100vh)",
      width: "100%",
      borderRadius: "4px"
    });

var Style = {
  wrapper: wrapper
};

function PlayerMinimal(props) {
  var options = props.options;
  var url = props.url;
  var videoRef = React.useRef(null);
  var playerRef = React.useRef(null);
  React.useEffect((function () {
          var video = playerRef.current;
          if (video === null || video === undefined) {
            video === null;
          } else {
            var autoplay = options.autoplay;
            if (autoplay !== undefined) {
              video.autoplay(autoplay);
            }
            video.src(url);
            return ;
          }
          var ref = videoRef.current;
          if (ref === null || ref === undefined) {
            return ;
          }
          var videoElement = document.createElement("video-js");
          var $$class = " video-js vjs-big-play-centered vjs-fill  " + Typo.Regular.headline2Force;
          videoElement.className = $$class;
          ref.appendChild(videoElement);
          playerRef.current = videoElement;
          var newrecord = Caml_obj.obj_dup(options);
          newrecord.loop = true;
          newrecord.controls = false;
          newrecord.autoplay = "muted";
          var video$1 = VideoJs(videoElement, newrecord);
          playerRef.current = video$1;
          video$1.ready((function () {
                  return Caml_option.nullable_to_opt(video$1.src(url));
                }), true);
        }), [videoRef]);
  React.useEffect((function () {
          return (function () {
                    var video = playerRef.current;
                    if (video === null || video === undefined || video.isDisposed()) {
                      return ;
                    } else {
                      video.dispose();
                      playerRef.current = null;
                      return ;
                    }
                  });
        }), [playerRef]);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    ref: Caml_option.some(videoRef),
                    className: " video-js vjs-fill " + Typo.Regular.headline2Force
                  }),
              className: wrapper
            });
}

var make = PlayerMinimal;

export {
  Style ,
  make ,
}
/*  Not a pure module */
