open StorybookMini

let default: meta<MovieBlockCards.props> = {
  title: "Organisms/MovieBlock/MovieBlockCards",
  component: MovieBlockCards.make,
}

let withSeeAll: storyObj<MovieBlockCards.props> = {
  args: {
    title: Some("Recently Added"),
    link: Some("/fr/videos/RC-024031/recently-added"),
    cards: [
      (
        {
          id: "1",
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
      kindLabel: None,
      forceLabel: None,
          alt: "Movie Poster",
          href: "",
          title: "yo",
          duration: None,
          durationLabel: None,
          orientation: Horizontal,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
      (
        {
          id: "1",
      kindLabel: None,
      forceLabel: None,
          srcBase: "https://api-cdn.arte.tv/img/v2/image/P2nRqjMQfKvVtrfMhgwoE/336x189?type=TEXT",
          alt: "Movie Poster",
          href: "",
          title: "yo",
          orientation: Horizontal,
          duration: None,
          durationLabel: None,
        },
        {
          img: "https://api-cdn.arte.tv/img/v2/image/NL8zV8YeVTdS3ay4ihnf8b/336x189?type=TEXT",
          href: "https://kinoo.dev",
          description: Some(
            "The recent national security law continues to brutally restrict freedoms as China tightens its grip on the territory.",
          ),
          ageRestriction: Some("+16"),
          audios: Some(["VF", "VO"]),
        },
      ),
    ],
  },
}
