// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Typo from "./Typo.res.mjs";
import * as Colors from "./Colors.res.mjs";
import * as Css from "@emotion/css";
import * as JsxRuntime from "react/jsx-runtime";

function Text$Regular$Headline1(props) {
  return JsxRuntime.jsx("h2", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.headline1,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Headline1 = {
  make: Text$Regular$Headline1
};

function Text$Regular$Headline2(props) {
  return JsxRuntime.jsx("h2", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.headline2,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Headline2 = {
  make: Text$Regular$Headline2
};

function Text$Regular$Title1(props) {
  return JsxRuntime.jsx("h2", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.title1,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Title1 = {
  make: Text$Regular$Title1
};

function Text$Regular$Title2(props) {
  return JsxRuntime.jsx("h2", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.title2,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Title2 = {
  make: Text$Regular$Title2
};

function Text$Regular$Body(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.body,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Body = {
  make: Text$Regular$Body
};

function Text$Regular$SmallBody(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.smallBody,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var SmallBody = {
  make: Text$Regular$SmallBody
};

function Text$Regular$SmallBodyGreen(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Regular.smallBody,
                    Colors.$$Text.secondaryGreen
                  ])
            });
}

var SmallBodyGreen = {
  make: Text$Regular$SmallBodyGreen
};

var Regular = {
  Headline1: Headline1,
  Headline2: Headline2,
  Title1: Title1,
  Title2: Title2,
  Body: Body,
  SmallBody: SmallBody,
  SmallBodyGreen: SmallBodyGreen
};

function Text$Medium$Title3(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Medium.title3,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Title3 = {
  make: Text$Medium$Title3
};

function Text$Medium$Headline2(props) {
  return JsxRuntime.jsx("h2", {
              children: props.children,
              className: Css.cx([
                    Typo.Medium.title3,
                    Colors.$$Text.greyGrey_20
                  ])
            });
}

var Headline2$1 = {
  make: Text$Medium$Headline2
};

function Text$Medium$SmallBody(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Medium.smallBody,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var SmallBody$1 = {
  make: Text$Medium$SmallBody
};

function Text$Medium$SmallBodyGreen(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Medium.smallBody,
                    Colors.$$Text.secondaryGreen
                  ])
            });
}

var SmallBodyGreen$1 = {
  make: Text$Medium$SmallBodyGreen
};

var Medium = {
  Title3: Title3,
  Headline2: Headline2$1,
  SmallBody: SmallBody$1,
  SmallBodyGreen: SmallBodyGreen$1
};

function Text$Bold$Title1(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Css.cx([
                    Typo.Bold.title1,
                    Colors.$$Text.primaryWhite
                  ])
            });
}

var Title1$1 = {
  make: Text$Bold$Title1
};

var Bold = {
  Title1: Title1$1
};

export {
  Regular ,
  Medium ,
  Bold ,
}
/* Typo Not a pure module */
