// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as GreenfinityNext_Errors from "./GreenfinityNext_Errors.res.mjs";

var JsonDecodeError = /* @__PURE__ */Caml_exceptions.create("GreenfinityNext_Fetch.JsonDecodeError");

var $$Headers = {};

async function jsonResult(response) {
  var text = await response.text();
  try {
    return {
            TAG: "Ok",
            _0: JSON.parse(text)
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: text
            };
    }
    var obj$1 = obj._1;
    var match = obj$1.name;
    if (match !== undefined) {
      if (match === "SyntaxError") {
        return {
                TAG: "Error",
                _0: text
              };
      }
      throw {
            RE_EXN_ID: JsonDecodeError,
            _1: Belt_Option.getWithDefault(obj$1.message, ""),
            Error: new Error()
          };
    }
    throw {
          RE_EXN_ID: JsonDecodeError,
          _1: "",
          Error: new Error()
        };
  }
}

async function json(response) {
  return await response.json();
}

var FetchResponse = {
  jsonResult: jsonResult,
  json: json
};

function fetchJson(url, body) {
  var options = {
    method: "put",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  };
  return Js_promise2.then(fetch(url, options), (function (res) {
                if (res.ok) {
                  return res.json();
                }
                throw {
                      RE_EXN_ID: GreenfinityNext_Errors.ApiError,
                      _1: GreenfinityNext_Errors.apiErrorFromStatus(res.status),
                      Error: new Error()
                    };
              }));
}

function fetchJson0(url) {
  return fetchJson(url, null);
}

export {
  JsonDecodeError ,
  $$Headers ,
  FetchResponse ,
  fetchJson ,
  fetchJson0 ,
}
/* No side effect */
